const errorCodes = {
  NOT_FOUND: 1,
  INVALID_LOGIN_CREDENTIALS: 2,
  INVALID_TOKEN: 3,
  NO_TOKEN: 4,
  NOT_AUTHORIZED: 5,
  ALREADY_REGISTERED: 6,
  INVALID_USER_DATA: 7,
};

export default errorCodes;
